### PR TITLE
feat: add volume control & display

### PR DESCRIPTION
**Pull request by BrendanMesters**
Implemented issue #3 

I added a simple volume control to the program, using native functionality in `rodio::sink`.

This logic has also been linked through to the UI so that users will be aware of this fucntionality (bound to the '-' and '+' keys) and adding a volume readout to the UI as well.

### CODE REVIEW

**Comment by BrendanMesters** [comment]
I liked the project, but found I was missing a volume control, so I implemented it, feel free to merge it into the main project if its to your liking :-)

**Comment by talwat** [comment]
Hi! This all looks good, although perhaps adding support for Arrow Up, Down, Left & Right could make it even easier.

I think I'll also fork your repo and add a little indicator that might temporarily replace the bottom controls with a little volume bar, so you get some feedback whenever you change your volume without taking up any more space.

**Comment by BrendanMesters** [comment]
@talwat do note that I did change the spacing (the `WIDTH` variable) slightly when adding the indicator text at the bottom ("volume [+/-]"), so if you change that back, you probably also want to consider the width.

Besides that I'm totally fine with different looks, this was just the most intuitive way I though of. 
I also considered using a nerdfont character to indicate volume (as opposed to the text "Volume"), however, given that not everyone uses a nerdfont I chose against this.

also, adding many different key options ('+', '=', '<right>', '<up>' for volume up for example) should be almost no work. I would appreciate it if you did keep in the +, -, =, _ controls, even if you did extend it to keyboard also :-)

**Comment by BrendanMesters** [comment]
I was also thinking of maybe adding some functionality where you can have a toml file (in your .config) in which you can add extra sources (if you want to listen to other similar music libraries with this).

I haven't looked into the feasibility yet, but if you'd be interested then just let me know, I'd love to tinker a bit and see if its easily possible

**Comment by talwat** [comment]
> I would appreciate it if you did keep in the +, -, =, _ controls, even if you did extend it to keyboard also :-)

Yup, not a problem. I actually made a commit a few hours ago implementing just that.

About the UI, I think keeping the same size and replacing the bottom bar briefly is a good solution, since usually people will set the volume and then forget about it, so they only really need to see it when they're adjusting. I'm currently working on that too, so I think I can finish this PR off relatively soon.

**Comment by talwat** [comment]
> I was also thinking of maybe adding some functionality where you can have a toml file (in your .config) in which you can add extra sources (if you want to listen to other similar music libraries with this).

I think that's possible, however, to remain in the scope of the project it'd probably just be a super basic list of mp3 files with some hopefully descriptive names. But yeah, that's definitely possible :)

**Comment by Samsu-F** [comment]
Thank you to both of you for implementing my feature request! Could not have done it myself as I don't know anything about Rust.
I did however open a [pull request](https://github.com/BrendanMesters/lowfi/pull/1) downstream for a more fine-grained adjustment option

**Comment by talwat** [comment]
Alright, I implemented a rough version of the audio display I was mentioning.

https://github.com/user-attachments/assets/d47f4a16-16d7-4028-9c38-b9e4986fa8d8

The code is a bit wonky, but it gets the job done. Let me know your thoughts :)

**Comment by talwat** [comment]
Well, considering this is mostly complete, I'll merge the PR but keep the thread unlocked if there are any minor tweaks that should be done. https://github.com/BrendanMesters/lowfi/pull/1 can also be ported to this repo later down the line.

**Comment by BrendanMesters** [comment]
I don't fully agree with the UI decision to not display the volume button shortcuts as with Skip, Pause and Quit buttons, but its your project, so do what you want.

Besides that, I think that maybe a delay of 1 more second before the UI changes back might be nice :-)

**Comment by talwat** [comment]
> I don't fully agree with the UI decision to not display the volume button shortcuts as with Skip, Pause and Quit buttons, but its your project, so do what you want.

If you have any ideas for squeezing them in I'd be more than open to it. I'm not totally happy with it either, but part of lowfi's appeal is that it's so simple & small. If you can come up with a solution that doesn't increase the size & still looks good, I'd merge it in a heartbeat :)

> Besides that, I think that maybe a delay of 1 more second before the UI changes back might be nice :-)

Yeah, that part is a constant so it's super easy to tweak. It is counted in frames, because more complicated solutions are way out of scope and it's just a small music player not a video game so it should be fine. If people say it's too small of a window I'll just bump it up slightly.

**Comment by BrendanMesters** [comment]
I mean, it could be done with a nerdfont icon, but I personally prefer having important info shown, as I hide the terminal this is running in most of the time.

But no worries, I'll just keep my separate version of the UI on my own branch haha

**Pull request merged**
