### PR TITLE
add description of available controls

### PR DESCRIPTION
**Pull request by Timoyoungster**
add dedicated description for the available controls, since the volume control is not documented in the app.

### CODE REVIEW

**Comment by talwat** [comment]
I think the `up` & `down` parts are redundant, but otherwise I think this is a good solution.

**Comment by Timoyoungster** [comment]
Which part about the up down part do you mean?
The "or `up/down`" or the "volume **up/down**"?

**Comment by talwat** [comment]
Yeah, the "or `up/down`" part.

**Comment by talwat** [comment]
LGTM!

**Pull request merged**
