### PR TITLE
feat: initial support for mpris

### PR DESCRIPTION
**Pull request by talwat**
This adds initial & optional support for MPRIS.
It also overhauls part of the `Next` functionality which probably should've been this way since the beginning.

### CODE REVIEW

**Comment by talwat** [comment]
@omnigenous I think this PR is ready to be tested, could you see if it works on your end?

**Comment by talwat** [comment]
Well, I'm merging this PR since other features depend on it being merged (because the audio system had to be partially reworked), but I won't push out a new update until testing.

**Comment by timofurrer** [comment]
> It also overhauls part of the Next functionality which probably should've been this way since the beginning.

@talwat it's no longer auto-advancing to the next track for me on `main`. I suspect it has to do with this MR. Was that intentional?

**Comment by talwat** [comment]
> @talwat it's no longer auto-advancing to the next track for me on `main`. I suspect it has to do with this MR. Was that intentional? 

Not at all, but it's also why I test before releasing 😄

It should be fixed soon, for now just use the previous release of lowfi.

**Comment by talwat** [comment]
> @talwat it's no longer auto-advancing to the next track for me on `main`. I suspect it has to do with this MR. Was that intentional? 

Nope, it'll be fixed soon. I might've sent this message twice because the Github mobile app is very buggy.

**Comment by talwat** [comment]
Alright, could you try now with https://github.com/talwat/lowfi/commit/d9ba0c3b3b3dd07266e7cfeeb7c1adc03beaa496?

**Comment by timofurrer** [comment]
@talwat works! Thanks for fixing it. Any chance of cutting a release? :)

**Comment by talwat** [comment]
> @talwat works! Thanks for fixing it. Any chance of cutting a release? :)

Yep! Doing it now :)

**Comment by omnigenous** [comment]
OMG! This is so good, I can actually daily drive lowfi now 😃

I just pulled from main and one bug I found is that you can go into negative volume:

1. lowfi volume is 100%
2. `playerctl --player lowfi volume 1.1-`
3. `playerctl --player lowfi volume`
4. See `-0.100000`

lowfi treats negative numbers as positives, but that not a main issue. User should never be able to go to negative values.

Other than that implementation is perfect from my tests!

**Comment by talwat** [comment]
> lowfi treats negative numbers as positives, but that not a main issue. User should never be able to go to negative values.
> 
> Other than that implementation is perfect from my tests!

Whoopsies, another thing that should be an easy fix, but I didn't notice lmao. At least it's not as catastrophic as the other bug you mentioned :^)

**Pull request merged**
